name: Build SpinalHDL Container Image

on: 
  push:
    branches: [main]
    paths:
      - '.github/workflows/spinalhdl_container.yaml'
      - 'Containers/SpinalHDL/**'

jobs:
  # idea from here https://stackoverflow.com/questions/70249519/how-to-check-if-a-secret-variable-is-empty-in-if-conditional-github-actions
  check-secrets:
    name: Checking if Github Token is Provided
    runs-on: ubuntu-latest
    outputs:
      github-token-exists: ${{ steps.check-gh-token.outputs.defined }}
    steps:
        - id: check-gh-token
          env:
            GH_TOK: ${{ secrets.GITHUB_TOKEN }}
          if: "${{ env.GH_TOK != '' }}"
          run: echo "::set-output name=defined::true"

  build-spinalhdl-container:
    name: Build SpinalHDL Container
    runs-on: [linux, x64]
    needs: [check-secrets]
    permissions:
      packages: write
    
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Image Tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/spinalhdl
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{branch}}-latest
            type=raw,value={{branch}}-{{sha}}
            type=ref,event=tag
            type=ref,event=pr

      - name: Build SpinalHDL Container
        id: spinalhdl-container
        uses: docker/build-push-action@v2
        with:
          context: ./Containers/SpinalHDL
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ (needs.check-secrets.outputs.github-token-exists == 'true') }}
